<a href="https://colab.research.google.com/github/honey15/numpy_test/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

a=np.random .randint(1, 101, size=(3, 3))

In [8]:
a


array([[ 27,  76,  93],
       [100,  65,  82],
       [ 76,  74,  85]])

In [11]:
a.T


array([[61, 22, 30],
       [51, 92, 64],
       [24, 39, 52]])

In [21]:
#Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

tenelement= np.random.randint(1, 101, size=10)
tenelement



array([ 48,  66,  64,  88,  86,  24,  39, 100,  37,  56])

In [23]:
tenelement.reshape(2,5)



array([[ 48,  66,  64,  88,  86],
       [ 24,  39, 100,  37,  56]])

In [25]:
tenelement.reshape(5,2)



array([[ 48,  66],
       [ 64,  88],
       [ 86,  24],
       [ 39, 100],
       [ 37,  56]])

In [27]:
#Using NumPy, create an array of integers from 10 to 60 with a step of 5.

np.arange(10, 61, 5)


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [39]:
from re import S
#Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element

s=np.array(['Python', 'numpy', 'pandas'])
s




array(['Python', 'numpy', 'pandas'], dtype='<U6')

In [44]:
np.char.upper(s)


array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [45]:
np.char.lower(s)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [46]:
np.char.title(s)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [48]:
np.char.capitalize(s)


array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [49]:
#Generate a NumPy array of words. Insert a space between each character of every word in the array.

words=np.array(['python', 'numpy', 'pandas'])
words

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [52]:
Spacing=np.char.join(' ', words)
Spacing


array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

In [55]:
#Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

a1=np.random.randint(1,10,size=(3,3))

a2=np.random.randint(1,10,size=(3,3))


In [57]:
a1

array([[2, 3, 8],
       [2, 4, 1],
       [8, 7, 2]])

In [59]:
a2



array([[2, 5, 2],
       [3, 7, 5],
       [6, 3, 4]])

In [61]:
np.add(a1,a2)

array([[ 4,  8, 10],
       [ 5, 11,  6],
       [14, 10,  6]])

In [62]:
#Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [64]:
matrix=np.eye(5)
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
matrix[0,0]

1.0

In [68]:
matrix[1,1]

1.0

In [71]:
matrix[2,2]

1.0

In [73]:
matrix[3,3]

1.0

In [74]:
matrix[4,4]

1.0

In [80]:
#using diagonal function
m1=matrix.diagonal()
m1.astype(int)

array([1, 1, 1, 1, 1])

In [82]:
#Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in  this array.

num=np.random.randint(0,1000,size=100)
num

array([573, 521, 523, 750, 353, 334,  82, 502, 930,  47, 576, 532, 411,
       865, 149, 909, 499, 919, 843, 933, 295, 221, 572, 303, 992, 921,
       653, 921, 652, 744, 876, 149, 107, 271, 464, 965, 375, 334, 803,
       356, 622, 917, 463, 596, 383,  77, 209, 678, 559, 809, 623, 279,
       225, 469, 301, 315, 293, 214, 664, 873, 741, 333, 658, 543, 694,
         0, 822, 622, 344, 311, 385, 637, 163, 662, 855, 433, 771, 123,
       605, 225, 128, 468, 935, 479, 775, 706, 179, 906, 735,  40, 919,
       512, 198, 837, 704, 446, 389, 152, 209, 796])

In [90]:

import numpy as np
num = np.random.randint(0, 1000, size=100)
prime_numbers = []
for number in num:
  is_prime = True
  for i in range(2, int(number**0.5) + 1):
    if number % i == 0:
      is_prime = False
      break
  if is_prime:
    prime_numbers.append(number)
print(prime_numbers)


[167, 73, 13, 233, 151, 71, 337, 331, 103, 13, 479]


In [127]:
# Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
import numpy as np

# Example array with 30 elements
temp=np.random.randint(1,30,size=30)

In [129]:
temp

array([19,  3, 16, 21, 10, 27, 13, 28, 16, 13, 19, 29, 26, 24,  1, 20, 10,
       22, 18, 23, 20,  4, 19, 20, 27, 24, 17, 14,  2, 24])

In [133]:
tempreshape=temp.reshape(6,5)
tempreshape

array([[19,  3, 16, 21, 10],
       [27, 13, 28, 16, 13],
       [19, 29, 26, 24,  1],
       [20, 10, 22, 18, 23],
       [20,  4, 19, 20, 27],
       [24, 17, 14,  2, 24]])

In [135]:
tempreshape.mean(axis=1)

array([13.8, 19.4, 19.8, 18.6, 18. , 16.2])